# Generated by Django 4.2.7 on 2023-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_db_password_db_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
